# Generated by Django 3.0.7 on 2020-06-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20200623_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcdcData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('csv_file', models.FilePathField(path='/home/dannguyen/projects/covid19/data/ECDC')),
            ],
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
