# Generated by Django 3.0.7 on 2020-06-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20200629_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecdcdata',
            name='csv_file',
            field=models.FilePathField(path='data/ECDC'),
        ),
        migrations.AlterField(
            model_name='jhudata',
            name='csv_file',
            field=models.FilePathField(path='data/JHU'),
        ),
        migrations.AlterField(
            model_name='vndata',
            name='csv_file',
            field=models.FilePathField(verbose_name='data/VN'),
        ),
    ]
