# Generated by Django 3.0.7 on 2020-06-29 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20200629_0807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecdcdata',
            old_name='csv_file',
            new_name='csvFile',
        ),
        migrations.RenameField(
            model_name='jhudata',
            old_name='csv_file',
            new_name='csvFile',
        ),
        migrations.RenameField(
            model_name='vndata',
            old_name='csv_file',
            new_name='csvFile',
        ),
        migrations.RenameField(
            model_name='vndata',
            old_name='data_type',
            new_name='dataType',
        ),
    ]
