# Generated by Django 3.0.7 on 2020-07-04 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20200629_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecdcdata',
            old_name='csvFile',
            new_name='csv_file',
        ),
        migrations.RenameField(
            model_name='jhudata',
            old_name='csvFile',
            new_name='csv_file',
        ),
        migrations.RenameField(
            model_name='vndata',
            old_name='csvFile',
            new_name='csv_file',
        ),
        migrations.RenameField(
            model_name='vndata',
            old_name='dataType',
            new_name='data_type',
        ),
    ]
